version: '3.9'
services:
  app_blue:
    image: ghcr.io/adonai-24/tattoo-bluegreen:main
    environment:
      - DEPLOY_ENV=blue
    ports:
      - '3001:3000'

  app_green:
    image: ghcr.io/adonai-24/tattoo-bluegreen:main
    environment:
      - DEPLOY_ENV=green
    ports:
      - '3002:3000'
